List<Map> myJson = [
  {
    'id':'ar',
    'image':'assets/flags/arabic.svg',
  },
  {
    'id':'en',
    'image':'assets/flags/us.svg',
  },
  {
    'id':'ger',
    'image':'assets/flags/german.svg',
  },
  {
    'id':'fr',
    'image':'assets/flags/france.svg',
  },
  {
    'id':'es',
    'image':'assets/flags/spain.svg',
  },
  {
    'id':'it',
    'image':'assets/flags/italy.svg',
  },
  {
    'id':'se',
    'image':'assets/flags/sweden.svg',
  },
  {
    'id':'tr',
    'image':'assets/flags/turkey.svg',
  },
  {
    'id':'jp',
    'image':'assets/flags/japan.svg',
  },
];